#!/usr/bin/env bash
#
# Packages what's needed to restore this node's IDENTITY on another
# machine (or the same one, after a reformat):
#   - config/priv_validator_key.json  (consensus key — signs blocks)
#   - config/node_key.json            (p2p identity — same node_id)
#   - data/priv_validator_state.json  (avoids double-sign when restoring)
#   - keyring-file/                   (accounts; already encrypted with the
#                                       keyring's own password)
#
# Does NOT include the plaintext mnemonic (the *-key-DO-NOT-SHARE.txt file
# generated by create-key.sh/init-chain.sh) — it's your responsibility to
# store that separately, in a password vault.
#
# Usage:
#   ./scripts/backup-node.sh
#   BACKUP_DIR=/mnt/usb-drive ./scripts/backup-node.sh
#
# Restore with: ./scripts/restore-node.sh <generated-file>

set -euo pipefail

# ---------------------------------------------------------------------------
# Variables — edit here
# ---------------------------------------------------------------------------

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HOME_DIR="${HOME_DIR:-$HOME/.aiontherad}"

# Where to save the package. The goal is to move this OFF this machine
# as soon as possible (USB drive, password vault, separate storage) — it's
# not meant to stay only here, even though the default lands inside the repo
# (it's already in .gitignore, but that's not a real backup).
BACKUP_DIR="${BACKUP_DIR:-$REPO_ROOT/backups}"

# true: encrypts the package with gpg (symmetric passphrase, prompts interactively).
# Strongly recommended whenever the backup is going to leave this machine.
ENCRYPT="${ENCRYPT:-true}"

# Optional: skips the interactive prompt below by feeding this passphrase
# directly. Meant for trusted automation only — avoid passing secrets via
# environment variable in interactive/shared sessions. If left empty, the
# script prompts for it below (hidden input), instead of relying on gpg's
# own pinentry, which can break over plain SSH (no tty/curses).
BACKUP_PASSPHRASE="${BACKUP_PASSPHRASE:-}"

# Includes the full "file" keyring (accounts) in the package. It's already
# encrypted with the keyring's own password, so including it is safe. Turn
# this off if you'd rather recover accounts separately via import-key.sh +
# mnemonic.
INCLUDE_KEYRING="${INCLUDE_KEYRING:-true}"

TIMESTAMP="$(date +%Y%m%d-%H%M%S)"
MONIKER_HINT="$(basename "$HOME_DIR")"
ARCHIVE_NAME="aionthera-backup-${MONIKER_HINT}-${TIMESTAMP}.tar.gz"

# ---------------------------------------------------------------------------
# Initial checks
# ---------------------------------------------------------------------------

if [[ ! -f "$HOME_DIR/config/priv_validator_key.json" ]]; then
  echo "Couldn't find $HOME_DIR/config/priv_validator_key.json"
  echo "Has this node been initialized (init-chain.sh / join-network.sh)?"
  exit 1
fi

mkdir -p "$BACKUP_DIR"

# ---------------------------------------------------------------------------
# Build the file list (paths relative to HOME_DIR)
# ---------------------------------------------------------------------------

FILES=(
  "config/priv_validator_key.json"
  "config/node_key.json"
)

if [[ -f "$HOME_DIR/data/priv_validator_state.json" ]]; then
  FILES+=("data/priv_validator_state.json")
fi

if [[ "$INCLUDE_KEYRING" == "true" && -d "$HOME_DIR/keyring-file" ]]; then
  FILES+=("keyring-file")
fi

echo ">> Packaging from $HOME_DIR:"
printf '   - %s\n' "${FILES[@]}"

TMP_TAR="$(mktemp --suffix=.tar.gz)"
tar -czf "$TMP_TAR" -C "$HOME_DIR" "${FILES[@]}"

# ---------------------------------------------------------------------------
# Optional encryption
# ---------------------------------------------------------------------------

FINAL_PATH="$BACKUP_DIR/$ARCHIVE_NAME"

if [[ "$ENCRYPT" == "true" ]]; then
  if ! command -v gpg >/dev/null 2>&1; then
    echo "ENCRYPT=true but gpg is not installed (apt install gnupg / pacman -S gnupg)."
    echo "Generating WITHOUT encryption — encrypt manually before moving it off this machine."
    mv "$TMP_TAR" "$FINAL_PATH"
  else
    if [[ -z "$BACKUP_PASSPHRASE" ]]; then
      echo ">> Choose a backup passphrase (strong; you'll need it to restore)"
      read -r -s -p "Passphrase: " BACKUP_PASSPHRASE
      echo
      read -r -s -p "Confirm passphrase: " BACKUP_PASSPHRASE_CONFIRM
      echo
      if [[ "$BACKUP_PASSPHRASE" != "$BACKUP_PASSPHRASE_CONFIRM" ]]; then
        echo "Passphrases don't match. Aborting."
        exit 1
      fi
      unset BACKUP_PASSPHRASE_CONFIRM
    fi
    echo ">> Encrypting with gpg"
    printf '%s' "$BACKUP_PASSPHRASE" | gpg --batch --yes --pinentry-mode loopback --passphrase-fd 0 \
      --symmetric --cipher-algo AES256 --output "${FINAL_PATH}.gpg" "$TMP_TAR"
    rm -f "$TMP_TAR"
    FINAL_PATH="${FINAL_PATH}.gpg"
  fi
else
  mv "$TMP_TAR" "$FINAL_PATH"
fi

chmod 600 "$FINAL_PATH"

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------

echo
echo "======================================================================"
echo "Backup created: $FINAL_PATH"
echo "======================================================================"
echo
echo "IMPORTANT:"
echo "  - This file contains the validator's consensus key. Whoever has"
echo "    access to it can run a node signing blocks as if they"
echo "    were you — treat it like a private key."
echo "  - Move it off this machine NOW (USB drive, password vault,"
echo "    separate storage). Don't leave it only in this repo's backups/ folder."
echo "  - Does NOT include the account mnemonic (*-key-DO-NOT-SHARE.txt)."
echo "    Store that separately, in a password vault."
echo "  - Restore with: ./scripts/restore-node.sh $FINAL_PATH"
echo "======================================================================"
