#!/usr/bin/env bash
#
# Restores a package generated by scripts/backup-node.sh: consensus key,
# p2p identity key, validator state and (if included) the "file"
# keyring.
#
# Run this AFTER join-network.sh (which handles genesis + peers) and BEFORE
# start-chain.sh — this script overwrites the priv_validator_key.json and
# node_key.json that join-network.sh's `init` just generated.
#
# Usage:
#   ./scripts/restore-node.sh /path/aionthera-backup-....tar.gz.gpg

set -euo pipefail

# ---------------------------------------------------------------------------
# Variables
# ---------------------------------------------------------------------------

HOME_DIR="${HOME_DIR:-$HOME/.aiontherad}"
BACKUP_FILE="${1:-}"

# Optional: skips the interactive prompt below by feeding this passphrase
# directly. See the same variable in backup-node.sh.
BACKUP_PASSPHRASE="${BACKUP_PASSPHRASE:-}"

if [[ -z "$BACKUP_FILE" ]]; then
  echo "Usage: $0 /path/to/aionthera-backup-....tar.gz[.gpg]"
  exit 1
fi

if [[ ! -f "$BACKUP_FILE" ]]; then
  echo "File not found: $BACKUP_FILE"
  exit 1
fi

if [[ ! -f "$HOME_DIR/config/genesis.json" ]]; then
  echo "Couldn't find genesis at $HOME_DIR/config/genesis.json"
  echo "Run scripts/join-network.sh first (genesis + peers) — this script only handles the keys."
  exit 1
fi

# ---------------------------------------------------------------------------
# Double-sign warning — reason for the explicit confirmation below
# ---------------------------------------------------------------------------

echo "======================================================================"
echo "WARNING — double-sign / slashing risk"
echo "======================================================================"
echo "This backup contains the SAME consensus key (priv_validator_key.json)"
echo "as another node. If that other node (or any copy of this key)"
echo "is still running and signing blocks somewhere, running this"
echo "node in parallel with the same key could make you sign two"
echo "different blocks at the same height — this is detected by the"
echo "network and results in slashing (loss of part of the stake), with no way back."
echo
echo "Only continue if you are certain the original node is SHUT DOWN"
echo "and won't come back online with this key."
echo "======================================================================"
echo
read -r -p "Type CONFIRM to continue: " CONFIRM
if [[ "$CONFIRM" != "CONFIRM" ]]; then
  echo "Aborted."
  exit 1
fi

# ---------------------------------------------------------------------------
# Decryption + extraction
# ---------------------------------------------------------------------------

TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

TAR_PATH="$BACKUP_FILE"
if [[ "$BACKUP_FILE" == *.gpg ]]; then
  if ! command -v gpg >/dev/null 2>&1; then
    echo ".gpg file but gpg is not installed. Install it before continuing."
    exit 1
  fi
  TAR_PATH="$TMP_DIR/backup.tar.gz"
  if [[ -z "$BACKUP_PASSPHRASE" ]]; then
    read -r -s -p "Backup passphrase: " BACKUP_PASSPHRASE
    echo
  fi
  echo ">> Decrypting"
  printf '%s' "$BACKUP_PASSPHRASE" | gpg --batch --yes --pinentry-mode loopback --passphrase-fd 0 \
    --decrypt --output "$TAR_PATH" "$BACKUP_FILE"
fi

echo ">> Extracting"
mkdir -p "$TMP_DIR/extracted"
tar -xzf "$TAR_PATH" -C "$TMP_DIR/extracted"

if [[ ! -f "$TMP_DIR/extracted/config/priv_validator_key.json" ]]; then
  echo "Invalid backup: couldn't find config/priv_validator_key.json after extracting."
  exit 1
fi

# ---------------------------------------------------------------------------
# Save what's currently in HOME_DIR before overwriting (never lose the
# current keys without leaving a copy)
# ---------------------------------------------------------------------------

SAFETY_DIR="$HOME_DIR/pre-restore-backup-$(date +%Y%m%d-%H%M%S)"
mkdir -p "$SAFETY_DIR/config" "$SAFETY_DIR/data"

[[ -f "$HOME_DIR/config/priv_validator_key.json" ]] && cp "$HOME_DIR/config/priv_validator_key.json" "$SAFETY_DIR/config/"
[[ -f "$HOME_DIR/config/node_key.json" ]] && cp "$HOME_DIR/config/node_key.json" "$SAFETY_DIR/config/"
[[ -f "$HOME_DIR/data/priv_validator_state.json" ]] && cp "$HOME_DIR/data/priv_validator_state.json" "$SAFETY_DIR/data/"

echo ">> Current keys (generated by init) saved to: $SAFETY_DIR"

# ---------------------------------------------------------------------------
# Restore
# ---------------------------------------------------------------------------

cp "$TMP_DIR/extracted/config/priv_validator_key.json" "$HOME_DIR/config/priv_validator_key.json"
echo ">> priv_validator_key.json restored"

if [[ -f "$TMP_DIR/extracted/config/node_key.json" ]]; then
  cp "$TMP_DIR/extracted/config/node_key.json" "$HOME_DIR/config/node_key.json"
  echo ">> node_key.json restored (same node_id as before)"
fi

if [[ -f "$TMP_DIR/extracted/data/priv_validator_state.json" ]]; then
  mkdir -p "$HOME_DIR/data"
  cp "$TMP_DIR/extracted/data/priv_validator_state.json" "$HOME_DIR/data/priv_validator_state.json"
  echo ">> priv_validator_state.json restored"
fi

if [[ -d "$TMP_DIR/extracted/keyring-file" ]]; then
  if [[ -d "$HOME_DIR/keyring-file" ]]; then
    mv "$HOME_DIR/keyring-file" "$SAFETY_DIR/keyring-file-old"
  fi
  cp -r "$TMP_DIR/extracted/keyring-file" "$HOME_DIR/keyring-file"
  echo ">> keyring-file restored (accounts from the backup)"
fi

chmod -R go-rwx "$HOME_DIR/config" 2>/dev/null || true
[[ -d "$HOME_DIR/keyring-file" ]] && chmod -R go-rwx "$HOME_DIR/keyring-file" 2>/dev/null || true

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------

echo
echo "======================================================================"
echo "Restore complete."
echo "======================================================================"
echo "Next steps:"
echo "  1) HOME_DIR=$HOME_DIR CHAIN_ID=<chain-id> ./scripts/start-chain.sh"
echo "  2) Wait for it to sync (catching_up: false):"
echo "     curl -s http://127.0.0.1:26657/status | jq '.result.sync_info'"
echo "  3) If the validator was jailed because of the downtime, send the unjail tx:"
echo "     aiontherad --home $HOME_DIR tx slashing unjail --from <account> --chain-id <chain-id>"
echo "======================================================================"
